name: Lint

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install packages and check syntax
      run: |
        yarn install
        yarn lint:ci
        yarn lint:css
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
    - name: Slack notification FAILED
      uses: itsmelion/action-slack@feature/refactor-config
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: "Lint *FAILED* at {{ GITHUB_REPOSITORY }}\n Dude, your code sucks.."

    - name: Slack notification SUCCESS
      uses: itsmelion/action-slack@feature/refactor-config
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: "Lint *SUCCESS!* at {{ GITHUB_REPOSITORY }}\n One more step to a glorious future."
