name: Lint stuff

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install packages and check syntax
      run: |
        yarn install
        yarn lint:ci
        yarn lint:css
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
    - name: Slack notification FAIL
      uses: Ilshidur/action-slack@1.0.1
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_OVERRIDE_MESSAGE: true
      with:
        args: '*FAILED* Dude, your code sucks..'
    - name: Slack notification SUCCESS
      uses: Ilshidur/action-slack@1.0.1
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_OVERRIDE_MESSAGE: true
      with:
        args: '*Success!* One more step to a glorious future.'
